name: pravega
version: 0.6.1
appVersion: 0.6.1
description: Bookkeeper Helm chart for Kubernetes
keywords:
- pravega
- storage
home: https://github.com/pravega/pravega
icon: https://avatars3.githubusercontent.com/u/25698199
sources:
- https://github.com/pravega/pravega
engine: gotpl
