apiVersion: v2
name: pravega-bk
description: Bookkeeper Helm chart for Kubernetes
version: 0.1.0
keywords:
  - log storage
  - stream storage
home: https://github.com/apache/bookkeeper
icon: https://bookkeeper.apache.org/images/bookkeeper_logo_blk.png
