## Default values for bookkeeper.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

version: 0.7.0

image:
  repository: pravega/bookkeeper
  pullPolicy: IfNotPresent

hooks:
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10

replicas: 3
zookeeperUri: zk-client:2181
pravegaClusterName: pravega
autoRecovery: true

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

storage:
  ledger:
    className: standard
    volumeSize: 10Gi
  journal:
    className: standard
    volumeSize: 10Gi
  index:
    className: standard
    volumeSize: 10Gi

jvmOptions:
  memoryOpts: []
  gcOpts: []
  gcLoggingOpts: []
  extraOpts: []

options:
  # useHostNameAsBookieID: "true"
