apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega-bk"

spec:
  replicas: 3

  image:
    repository: pravega/bookkeeper
    pullPolicy: IfNotPresent

  version: latest
  zookeeperUri: zookeeper-client:2181
  autoRecovery: true
