apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: "pravega"

spec:
  replicas: 3

  image:
    repository: pravega/bookkeeper
    pullPolicy: IfNotPresent

  version: latest
  zookeeperUri: zk-client:2181
  autoRecovery: true
