apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookkeeper-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bookkeeper-operator
  template:
    metadata:
      labels:
        name: bookkeeper-operator
        component: bookkeeper-operator
    spec:
      serviceAccountName: bookkeeper-operator
      containers:
        - name: bookkeeper-operator
          image: pravega/bookkeeper-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - bookkeeper-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bookkeeper-operator"
