apiVersion: "bookkeeper.pravega.io/v1alpha1"
kind: "BookkeeperCluster"
metadata:
  name: {{ template "bookkeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bookkeeper.commonLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  image:
    repository: {{ .Values.image.repository }}
    pullPolicy: {{ .Values.image.pullPolicy }}
  version: {{ .Values.version }}
  zookeeperUri: {{ .Values.zookeeperUri }}
  envVars: {{ template "bookkeeper.fullname" . }}-configmap
  autoRecovery: {{ .Values.autoRecovery }}
  blockOwnerDeletion: {{ default true .Values.blockOwnerDeletion }}
  {{- if .Values.probes }}
  probes:
    {{- if .Values.probes.readiness }}
    readinessProbe:
      {{- if .Values.probes.readiness.initialDelaySeconds }}
      initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
      {{- end }}
      {{- if .Values.probes.readiness.periodSeconds }}
      periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
      {{- end }}
      {{- if .Values.probes.readiness.failureThreshold }}
      failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
      {{- end }}
      {{- if .Values.probes.readiness.successThreshold }}
      successThreshold: {{ .Values.probes.readiness.successThreshold }}
      {{- end }}
      {{- if .Values.probes.readiness.timeoutSeconds }}
      timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
      {{- end }}
    {{- end }}
    {{- if .Values.probes.liveness }}
    livenessProbe:
      {{- if .Values.probes.liveness.initialDelaySeconds }}
      initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
      {{- end }}
      {{- if .Values.probes.liveness.periodSeconds }}
      periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
      {{- end }}
      {{- if .Values.probes.liveness.failureThreshold }}
      failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
      {{- end }}
      {{- if .Values.probes.liveness.successThreshold }}
      successThreshold: {{ .Values.probes.liveness.successThreshold }}
      {{- end }}
      {{- if .Values.probes.liveness.timeoutSeconds }}
      timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.resources }}
  resources:
{{ toYaml .Values.resources | indent 6 }}
  {{- end }}
  storage:
    ledgerVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.ledger.className }}
      resources:
        requests:
          storage: {{ .Values.storage.ledger.volumeSize }}
    journalVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.journal.className }}
      resources:
        requests:
          storage: {{ .Values.storage.journal.volumeSize }}
    indexVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.index.className }}
      resources:
        requests:
          storage: {{ .Values.storage.index.volumeSize }}
  {{- if .Values.jvmOptions }}
  jvmOptions:
    memoryOpts:
{{ toYaml .Values.jvmOptions.memoryOpts | indent 6 }}
    gcOpts:
{{ toYaml .Values.jvmOptions.gcOpts | indent 6 }}
    gcLoggingOpts:
{{ toYaml .Values.jvmOptions.gcLoggingOpts | indent 6 }}
    extraOpts:
{{ toYaml .Values.jvmOptions.extraOpts | indent 6 }}
  {{- end }}
  {{- if .Values.options }}
  options:
{{ toYaml .Values.options | indent 4 }}
  {{- end }}
