kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "configmap.fullname" . }}
data:
  # Configuration values can be set as key-value properties
  PRAVEGA_CLUSTER_NAME: pravega
  WAIT_FOR: {{ .Values.zookeeperUri }}
