# workflow name
name: CI

# on events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# jobs to run
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.8
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.8
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Gofmt and License checks
      run: make check
    - name: unit tests
      run: make test-unit
